#User watch folder configuration
#Sun Jul 05 17:46:50 CST 2026
watch.action-poll-interval=500
watch.action-url=http\://192.168.43.154\:8000/output_results/backend_events/action_latest.json
watch.person-poll-interval=1000
watch.person-url=http\://192.168.43.154\:8000/output_results/backend_events/person_latest.json
watch.photo-http-url=http\://192.168.43.221\:8000/face
watch.photos-dir=C\:\\Users\\xffff\\Desktop\\user\\input_photos
